'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type MifielWidgetCustomEvent } from "@mifiel/widget";
import type { Components } from "@mifiel/widget/dist/components";
import { MifielWidget as MifielWidgetElement, defineCustomElement as defineMifielWidget } from "@mifiel/widget/dist/components/mifiel-widget.js";

export type MifielWidgetEvents = {
    onSignError: EventName<MifielWidgetCustomEvent<any>>,
    onSignSuccess: EventName<MifielWidgetCustomEvent<any>>
};

export const MifielWidget: StencilReactComponent<MifielWidgetElement, MifielWidgetEvents, Components.MifielWidget> = /*@__PURE__*/ createComponent<MifielWidgetElement, MifielWidgetEvents, Components.MifielWidget>({
    tagName: 'mifiel-widget',
    elementClass: MifielWidgetElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {
        onSignError: 'signError',
        onSignSuccess: 'signSuccess'
    } as MifielWidgetEvents,
    defineCustomElement: defineMifielWidget
});
